brain_node:
  ros__parameters:
    game:
      team_id: 31
      player_id: 0
      field_type: "adult_size"
      player_role: "striker"
      player_start_pos: "left"
      
    robot:
      robot_height: 1.0
      odom_factor: 1.2
      vx_factor: 0.90
      yaw_offset: 0.10
    
    enable_com: true

    rerunLog:
      enable: true
      server_addr: "192.168.5.23:9876"
      img_interval: 1
