show_res: false
camera:
  type: realsense
  intrin:
    fx: 642.753418
    fy: 642.111084
    cx: 643.532227
    cy: 367.085724
    distortion_model: 1
    distortion_coeffs:
    - -0.0561492667
    - 0.0654542521
    - -0.000988338375
    - 0.000662671111
    - -0.0213696938
  extrin:
  -
    - 0.05659255
    - 0.03014561
    - 0.99794215
    - 0.04217854
  -
    - -0.99839673
    - 0.00283376
    - 0.05653273
    - 0.01405556
  -
    - -0.00112372
    - -0.9995415
    - 0.03025765
    - -0.01538294
  -
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  pitch_compensation: 0.0
  yaw_compensation: 0.0
  z_compensation: 0.0
detection_model:
  model_path: ./src/vision/model/best_orin_10.3.engine
  confidence_threshold: 0.2
use_depth: true
ball_pose_estimator:
  use_depth: False
  radius: 1.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
human_like_pose_estimator:
  use_depth: False
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
