show_res: false
camera:
  type: realsense
  intrin:
    fx: 643.581665
    fy: 642.838074
    cx: 643.735657
    cy: 368.360596
    distortion_model: 1
    distortion_coeffs:
    - -0.0560964011
    - 0.0661926344
    - -0.000320490479
    - -9.39076053e-05
    - -0.021277396
  extrin:
  -
    - 0.00180072302
    - -0.026696682
    - 0.999642015
    - 0.0096466681
  -
    - -0.999998271
    - 0.000545835879
    - 0.00181594212
    - -0.028836485
  -
    - -0.000594120007
    - -0.999643326
    - -0.0266956501
    - -0.0209911671
  -
    - 0
    - 0
    - 0
    - 1
  pitch_compensation: 0
  yaw_compensation: 0
  z_compensation: 0
detection_model:
  model_path: ./src/vision/model/best_orin_10.3.engine
  confidence_threshold: 0.2
use_depth: true
ball_pose_estimator:
  use_depth: False
  radius: 1.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
human_like_pose_estimator:
  use_depth: False
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
calibration:
  handeye:
    calibration_time: 2025-07-17-14-08-48
    reprojection_error: 2.21493640223627
